name=Voice_Controller_Using_NLP_Library
version=1.0.0
author=Krishna
maintainer=ks0397747@gmail.com
sentence=A library for capturing audio from INMP441 microphone using I2S protocol.
paragraph=This library allows the ESP32 to read audio data from the INMP441 digital microphone via the I2S protocol, making it easier to integrate audio functionalities into project of Voive controller using NLP
category=Signal Input/Output
url=https://github.com/krishnasharma45/Voice_Controller_Using_NLP
architectures=*
